# Generated by Django 5.2.7 on 2025-10-24 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miniDataview', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='name',
            field=models.CharField(default='xd', max_length=200),
            preserve_default=False,
        ),
    ]
